export default {
    user:[
        {
            id: 1,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '' ,
            isFriend: true,
            isDeleted: false,
            hovered: false
        },
        {
            id: 2,
            firstName: 'Raymond',
            lastName: 'Ativie',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: true,
            isDeleted: false,
            hovered: false
        },
        {
            id: 3,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '' ,
            isFriend: false,
            isDeleted: false,
            hovered: false,
        },
        {
            id: 4,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '' ,
            isFriend: false,
            isDeleted: false,
            hovered: false,

        },
        {
            id: 5,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false,
        },
        {
            id: 6,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false,
        },
        {
            id: 7,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false,
        },
        {
            id: 8,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 9,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 10,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 11,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 12,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 13,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 14,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 15,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 16,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 17,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 18,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 19,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 20,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
        {
            id: 21,
            firstName: 'Seyi',
            lastName: 'Joseph',
            email: 'Seyi@gmail.com',
            phone: 808373783833,
            job: '',
            company: '',
            notes: '',
            isFriend: false,
            isDeleted: false,
            hovered: false, 
        },
    ]
}
